### ISSUE TITLE
Does it crawl the whole site?

### ISSUE THREAD

**Issue by z72diego** [icamys/php-sitemap-generator#10]
Hi there, im testing your script.

Does it crawl the whole site or just the specified urls?

Thanks

**Comment by icamys** [comment]
@z72diego This package does not crawl site at all. It only accept given URLs and generates the sitemap into files. Optionally it updates provided robots.txt with sitemap path.

**Comment by z72diego** [comment]
Thank you sir, for users looking for what i wanted to, this was my solution: https://github.com/knyzorg/Sitemap-Generator-Crawler
