### ISSUE TITLE
Support for videos

### ISSUE THREAD

**Issue by markharding** [icamys/php-sitemap-generator#11]
It would be nice to support video sitemaps (https://support.google.com/webmasters/answer/80471). Happy to take a stab at this.

Would just adding a new parameter to `addURL` be acceptable?

**Comment by icamys** [comment]
@markharding I suppose that it could be appropriate to add a new parameter - an associative array with data for the video tag inside the sitemap. Any PR are welcome :)

**Comment by icamys** [comment]
@markharding Support for video sitemap added in 4.1.0. Please see the [releases page](https://github.com/icamys/php-sitemap-generator/releases).
