### ISSUE TITLE
Multiple Language Tag is not correct 

### ISSUE THREAD

**Issue by dexter-goopter** [icamys/php-sitemap-generator#18]
As per google document. https://support.google.com/webmasters/answer/189077
**Problem:** Multiple Language tags 
**Expected:** <xhtml:link/>
**Current:** <link/>

**Comment by dexter-goopter** [comment]
You can fix it by changing 
Class: FileSitemapGenerator 
Line: 478
codes 
`$tag = $row->addChild('link', null, null);`
to 
`$tag = $row->addChild(
                                'xhtml:link',
                                'www.url.ch' . '/' . $alternate['hreflang'],
                                'http://www.w3.org/1999/xhtml'
                            );`

**Comment by icamys** [comment]
@dexter-goopter Hey! Thanks for noting this. I'll take a look today at it.

**Comment by icamys** [comment]
@dexter-goopter The link you provided doesn't work anymore, however, Google has examples of language links provided in their docs:
![image](https://user-images.githubusercontent.com/6891299/103285032-a33db200-49e5-11eb-9f64-7e7a18e779d3.png)
Currently, the generator creates links the same way. Closing the issue.
