### ISSUE TITLE
The location is not correct from the sitemap-index output

### ISSUE THREAD

**Issue by bugrevealingbme** [icamys/php-sitemap-generator#19]
As you can see from here, the location is not correct.
https://techindeep.com/sitemap/sitemap-index.xml

Should have been like https://www.techindeep.com/sitemap/sitemap1.xml.gz not https://www.techindeep.com/sitemap1.xml.gz

**Comment by icamys** [comment]
@bugrevealingbme Hi. Sorry, could you provide a few more details so I could help you in any way if it is still relevant?

**Comment by icamys** [comment]
A new major version of sitemap is released. Please open issue if the problem repeats.

**Comment by gixxy22** [comment]
problem still exists, essentially this doesnt work:

// OPTIONAL. Setting a custom sitemap URL base in case if the sitemap files location
// is different from the website root. Most of the time this is unnecessary and can be skipped. 
$config->setSitemapIndexURL('https://example.com/sitemaps/');
