### ISSUE TITLE
Does not generate a sitemap

### ISSUE THREAD

**Issue by w4ugit** [icamys/php-sitemap-generator#21]
An example of my code

`$yourSiteUrl = 'https://optklin.com.ua';
        $outputDir = getcwd();
        $generator = new \Icamys\SitemapGenerator\SitemapGenerator($yourSiteUrl, $outputDir);
        $generator->toggleGZipFileCreation();
        $generator->setMaxURLsPerSitemap(50000);
        $generator->setSitemapFileName('/frontend/web/sitemap.xml');
        $generator->addURL('/', new \DateTime(), 'always', 0.5, []);
        $generator->createSitemap();
        $generator->writeSitemap();`

It only creates such a file

`<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <url>
    <loc>https://optklin.com.ua/</loc>
    <lastmod>2020-12-08T10:58:14+00:00</lastmod>
    <changefreq>always</changefreq>
    <priority>0.5</priority>
  </url>
</urlset>
`

**Comment by icamys** [comment]
@w4ugit Looks like you misunderstood a bit the purpose of the variable `$outputDir`. The `$outputDir` should store the directory where you expect the sitemap to be generated. And the name of the sitemap without any path should be passed to the method `setSitemapFileName()` (only `sitemap.xml`, not `/frontend/web/sitemap.xml`). So for your case, the following code will work:

```php
include 'src/SitemapGenerator.php';

use Icamys\SitemapGenerator\SitemapGenerator;

$yourSiteUrl = 'https://optklin.com.ua';
$outputDir = getcwd() . '/frontend/web/';
$generator = new SitemapGenerator($yourSiteUrl, $outputDir);
$generator->toggleGZipFileCreation();
$generator->setMaxURLsPerSitemap(50000);
$generator->setSitemapFileName('sitemap.xml');
$generator->addURL('/', new DateTime(), 'always', 0.5, []);
$generator->createSitemap();
$generator->writeSitemap();
```

Also, ensure that you have appropriate permissions for the directory you want to write the sitemap to.
