### ISSUE TITLE
Wrong format for alternate language link generated

### ISSUE THREAD

**Issue by raulrebane** [icamys/php-sitemap-generator#23]
Currently the generator outputs <link rel="alternate" hreflang="en" href="...
This does work for google search, but does not work for Yandex. In Yandex I get tons of errors because of this.
Searching for this I found that link must be <xhtml:link rel="alternate" hreflang="de" href=
for more details please see google instructions https://developers.google.com/search/docs/advanced/crawling/localized-versions

**Comment by icamys** [comment]
@raulrebane Thanks for the link! Much appreciated. I'll take a look at this today.

**Comment by icamys** [comment]
@raulrebane Just fixed it in [4.3.1](https://github.com/icamys/php-sitemap-generator/releases/tag/4.3.1). Please check that out.

**Comment by raulrebane** [comment]
Great. I will try it out tomorrow and see if its ok.

**Comment by raulrebane** [comment]
Confirmed. Works as expected. Thanks mate.
