### ISSUE TITLE
Not Working in PHP 8.0.11 Version!

### ISSUE THREAD

**Issue by seyitahmettanriver** [icamys/php-sitemap-generator#30]
In **PHP 8.0.11** it gives the following error.

`Fatal error: Uncaught Error: Class "Icamys\SitemapGenerator\FileSystem" not found in /var/www/vhosts/example.com/httpdocs/class/class.sitemap.generator.php:224 Stack trace: #0 /var/www/vhosts/example.com/httpdocs/cron.sitemap.generator.php(12): Icamys\SitemapGenerator\SitemapGenerator->__construct() #1 {main} thrown in /var/www/vhosts/example.com/httpdocs/class/class.sitemap.generator.php on line 224`

**Comment by icamys** [comment]
@seyitahmettanriver The error tells that the class is not found. I suggest you have not included the autoload file:
```php
include "vendor/autoload.php";
```

**Comment by icamys** [comment]
Closing this issue as there's no update for a long time.
