### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by Tigla** [icamys/php-sitemap-generator#35]
The SubmitsiteMap method does not take into account the response FALSE when executing CURL request
`PHP Error[8]: Trying to access array offset on value of type bool in file /vendor/icamys/php-sitemap-generator/src/SitemapGenerator.php at line 634`

**Comment by icamys** [comment]
@Tigla Thanks for noticing. Fixed in [4.4.1](https://github.com/icamys/php-sitemap-generator/releases/tag/4.4.1).
