### ISSUE TITLE
Notice & Fatal Error

### ISSUE THREAD

**Issue by alexonbstudio** [icamys/php-sitemap-generator#37]
Notice: Trying to access array offset on value of type bool in /webser/verlibs/icamys/php-sitemap-generator/src/SitemapGenerator.php on line 647

Fatal error: Uncaught RuntimeException: failed to run curl_exec, error: Could not resolve host: submissions.ask.com in /webserver/libs/icamys/php-sitemap-generator/src/SitemapGenerator.php:638 Stack trace: #0 /webserver/sitemap-php.php(99): Icamys\SitemapGenerator\SitemapGenerator->submitSitemap() #1 {main} thrown in /webserver/libs/icamys/php-sitemap-generator/src/SitemapGenerator.php on line 638

I trying without composer also.

**Comment by alexonbstudio** [comment]
now files.xml.gz create inside have sitemap.xml but have fatal error:
Fatal error: Uncaught RuntimeException: failed to run curl_exec, error: Could not resolve host: submissions.ask.com in C:\xampp\htdocs\dev.lan\website-project\libs\icamys\php-sitemap-generator\src\SitemapGenerator.php:638 Stack trace: #0 C:\xampp\htdocs\dev.lan\website-project\sitemap-php.php(99): Icamys\SitemapGenerator\SitemapGenerator->submitSitemap() #1 {main} thrown in C:\xampp\htdocs\dev.lan\website-project\libs\icamys\php-sitemap-generator\src\SitemapGenerator.php on line 638

**Comment by alexonbstudio** [comment]
> PHP8.0 / 8.1

**Comment by alexonbstudio** [comment]
![Capture d’écran 2022-06-22 020126](https://user-images.githubusercontent.com/65239996/174915902-72bd4a44-2f7f-4572-b0bc-e0514160359d.png)
exemple

**Comment by kasperkamperman** [comment]
Same issue here. Something goes wrong with the submission of the sitemap. Probably to ask.com. 
The script works fine if you turn submission off:
`//$generator->submitSitemap();`

**Comment by francogp** [comment]
It would be a good idea to be able to turn off some search engines so we can disable ask.com or others when they fail

**Comment by lithium720** [comment]
Just ran into this

Script should probably catch and skip with warning

**Comment by francogp** [comment]
It also fail All other search engines (except google). All of them disabled the sitemap upload, and implemented the IndexNow API. This should be implemented as a new feature.

**Comment by icamys** [comment]
All ping pages except Yandex are now removed, so I'm closing this thread. If anyone experiences the issue again, please provide code examples so I can reproduce the problem. Cheers!
