### ISSUE TITLE
Are alternative links for mutlilanguage pages supported?

### ISSUE THREAD

**Issue by davalb** [icamys/php-sitemap-generator#4]
Google supports this syntax to submit alternative links for other languages: https://webmasters.googleblog.com/2012/05/multilingual-and-multinational-site.html

Is it possible to generate a sitemap containing alternative links with this library?

**Comment by icamys** [comment]
@davalb Unfortunately this library does not support this feature as it meets the standard presented in https://www.sitemaps.org/ and there was no need in alternative links till now. However this feature looks interesting. Do you have a case where alternative links are needed?

**Comment by icamys** [comment]
@davalb The feature is useful and in latest 1.2.0 version I've added the support of alternative links.

**Comment by davalb** [comment]
That was quick! Thank you will try it out!
