### ISSUE TITLE
Could not resolve host: submissions.ask.com 

### ISSUE THREAD

**Issue by gfra54** [icamys/php-sitemap-generator#43]
Hello, it seems that ask.com has changed thei submission link, because at the moment php-sitemap-generator fails with the error

`PHP Fatal error:  Uncaught RuntimeException: failed to run curl_exec, error: Could not resolve host: submissions.ask.com in vendor\icamys\php-sitemap-generator\src\SitemapGenerator.php:638` and the domain is not found : http://submissions.ask.com/

Is it possible to remove it from the code ? Thanks

**Comment by FosterG4** [comment]
in file  vendor/icamys/php-sitemap-generator/src/SitemapGenerator.php

you can disable it with : 

```
    private $searchEngines = [
        "http://www.google.com/ping?sitemap=",
        /** "http://submissions.ask.com/ping?sitemap=", */
        "http://www.bing.com/ping?sitemap=",
        "http://www.webmaster.yandex.ru/ping?sitemap=",
    ];
```

**Comment by gfra54** [comment]
Hello, Thanks. Yes, I know, that but I don't plan to edit files in my vendor folder. They are installed with composer and I have multiple virtual machines created by scripts. This is not something I can do and that's why I think it should be corrected. SHould I create a pull request ?

**Comment by icamys** [comment]
@gfra54 Hi and thanks for the report. A pull request would be highly appreciated. Thanks!

**Comment by gfra54** [comment]
Will do ASAP. There is also a change in how bing does it (they use a per url system now).
I think I will make a pull request that let the user pass an array of search engines ping urls to the method, that will replace the default one.

**Comment by gfra54** [comment]
AN also thanks for this great package 👍 Helped a lot
