### ISSUE TITLE
Remove Google Ping

### ISSUE THREAD

**Issue by LeninZapata** [icamys/php-sitemap-generator#58]
According to these statements from Google, uploading the sitemap through the ping url provided by Google will no longer be allowed. Currently they are doing it based on a Google console API. It would be good if the creator of this repository had an API APP in Google Console, and that allowed uploading sitemaps based on individual or portioned API. This is done by the Rank Math WordPress plugin, it has a script made within the Google Console, for those who want to upload the urls that way within the plugin and for free. Please review this topic.

https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping

**Comment by icamys** [comment]
Hi @LeninZapata ! Thanks for the link. I'm preparing the next version of the sitemap where this endpoint will be removed. Cheers!
