### ISSUE TITLE
Multiple sitemap names

### ISSUE THREAD

**Issue by LeninZapata** [icamys/php-sitemap-generator#59]
Hello, I can't find the option to change the name of individual sitemaps and then have everything join the main sitemap.
I need a structure like this:

```
sitemap-post-1.xml
sitemap-post-2.xml
sitemap-tag-1.xml
sitemap-tag-2.xml
sitemap-category-1.xml
sitemap-category-2.xml
sitemap-index.xml
```

I try changing the name with the 'get Sitemap Filename' function but it only takes the final name and puts them all like this.
![image](https://github.com/icamys/php-sitemap-generator/assets/42600954/15b6f319-670d-4d21-9954-df141264d0b4)

My code is:

```
$generator = new SitemapGenerator($siteUrl, $outputDir);
$alternates = [
	['hreflang' => 'de', 'href' => "http://www.example.com/de"],
	['hreflang' => 'fr', 'href' => "http://www.example.com/fr"],
];

$datetimeStr = '2020-12-29T08:46:55+00:00';
$lastmod = new DateTime('2020-12-29T08:46:55+00:00');

$generator->setMaxUrlsPerSitemap(8);
$generator->setSitemapFilename('post-category.xml'); // Sitemap name1
for ($i = 0; $i < 20; $i++) {
	$generator->addURL("/path/to/page-$i/", $lastmod, 'always', 0.5, $alternates);
}
$generator->flush();


$generator->setMaxUrlsPerSitemap(5);
$generator->setSitemapFilename('post-tag.xml'); // Sitemap name2
for ($i = 0; $i < 20; $i++) {
	$generator->addURL("/path/to/page2-$i/", $lastmod, 'always', 0.5, $alternates);
}
$generator->flush();



$generator->finalize(); // Generate Index with all sitemaps-
```

How can I get the result I need?

**Comment by sanvu88** [comment]
it won't concatenate like you want, you'll have to manually create a file that looks like this. 

<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://example.com/post_category_index.xml</loc>
    <lastmod>2023-10-10T23:51:35Z</lastmod>
  </sitemap>
  <sitemap>
    <loc>https://example.com/post_tag_index.xml</loc>
    <lastmod>2023-10-10T23:51:35Z</lastmod>
  </sitemap>
</sitemapindex>

**Comment by LeninZapata** [comment]
I understand, I'm going to have to edit the library a little then to be able to have the result I need.

**Comment by icamys** [comment]
Hi @LeninZapata. Thank you for your question. This package does not provide such a feature and, honestly, there's no need for it as the final consumer of the the sitemap is meant to be only search engines. If you need to have URLs related to different categories in separate files, I'd suggest writing them in separate files without using this package. Cheers!
