### ISSUE TITLE
updateRobots() duplicates Sitemap when index is not required

### ISSUE THREAD

**Issue by sigma-technology** [icamys/php-sitemap-generator#8]
Thank you for creating a very useful generator.

I'm using the latest release and it appears there are two bugs in the `updateRobots()` method when the total number of URLs is less than `MAX_URLS_PER_SITEMAP` (therefore making the sitemap index **not** required).  The following Sitemap records are written to robots.txt in these scenarios...

1. When `MAX_URLS_PER_SITEMAP` is set to a number less than the total number of URLs (forcing the sitemap index to be required):

        Sitemap: https://www.mydomain.com/sitemap-index.xml

    _This is the correct behaviour, I believe._

2. **Without** GZ compression turned on:

        Sitemap: https://www.mydomain.com/sitemap.xml
        Sitemap: https://www.mydomain.com/sitemap.xml

    _The line should only be written once._

3. **With** GZ compression turned on:

        Sitemap: https://www.mydomain.com/sitemap.xml.gz
        Sitemap: https://www.mydomain.com/sitemap.xml.gz.gz

    _There should be two lines (one for .xml and one for .gz, but they are named incorrectly (.gz is added to the filename twice)._

I believe the offending code is on lines 488-490, and 494-496:

    if (!isset($this->sitemapIndex)) {
        $robotsFileContent .= "\nSitemap: " . $this->getSitemapFileName($this->sitemapFullURL);
    }

...because `sitemapIndex` is never set if the number of URLs is less than `MAX_URLS_PER_SITEMAP`.

I hope this makes sense, but if not please feel free to ask me for clarification.

**Comment by icamys** [comment]
@sigma-technology thank you for detailed description of the issue. I will see what can be done when I will have some free time.

**Comment by sigma-technology** [comment]
@icamys No problem, I am currently using it anyway but with GZ disabled, so it's inserting the Sitemap: line twice in my robots.txt but I assume (hopefully) that won't be a big problem for Google.

If I get any spare time I will try to do a Pull request with a fix.

**Comment by icamys** [comment]
@sigma-technology no need for PR. I started to work under next major version. At the beginning this repo was composed of several libraries for my own needs however now it is used by others so the code should be refactored and covered with tests. As soon as I find some time I will release next version with this and some other bugs fixed.

**Comment by sigma-technology** [comment]
@icamys That would be much appreciated, thank you.

**Comment by icamys** [comment]
@sigma-technology version 2.0.0 released, please tell if any bugs appear again

**Comment by sigma-technology** [comment]
@icamys Thank you, I've now had time to upgrade and test this, and it seems to be working great!

Only one small comment - when GZ is enabled, only the sitemap.xml.gz URL is added to robots.txt, which is absolutely fine as there's not much point in having both in there.  However, in the comment on [line 104](https://github.com/icamys/php-sitemap-generator/blob/ed0491f374999d17ba8ef1ae9043443b05907e9f/src/SitemapGenerator.php#L104) it says that both will be added to robots.txt, so maybe just amend this to avoid confused/future issues getting logged.

Thanks again for choosing to spend your time on this 👍 and feel free to close this issue if you feel it is now resolved.
